spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
      name: microconfig-test-client00000000
  

eureka:
 client:
  service-url:
    defaultZone: http://admin:a@localhost:7301/eureka
info:
  app.name: microservice-config-client-dev-updated
  company.name: yc222
---
server:
  port: 8102

spring:
  profiles: beta
  application:
      name: microconfig-test-client333

eureka:
 client:
  service-url:
    defaultZone: http://admin:a@localhost:7301/eureka
    
info:
  app.name: microservice-config-client-beta
  company.name: hyycinfo
